# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.IntegerField(db_index=True, verbose_name='Player 1')),
                ('player_2', models.IntegerField(db_index=True, verbose_name='Player 2')),
                ('win', models.IntegerField(default=0, verbose_name='\uc2b9')),
                ('lose', models.IntegerField(default=0, verbose_name='\ud328')),
                ('rating', models.FloatField(db_index=True, default=1000.0, verbose_name='\ub808\uc774\ud305')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='\uc774\ub984')),
                ('win', models.IntegerField(default=0, verbose_name='\uc2b9')),
                ('lose', models.IntegerField(default=0, verbose_name='\ud328')),
                ('rating', models.FloatField(db_index=True, default=1000.0, verbose_name='\ub808\uc774\ud305')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(auto_now=True, verbose_name='\ub4f1\ub85d \uc2dc\uac04')),
                ('play_date', models.DateTimeField(db_index=True, verbose_name='\uacbd\uae30 \uc2dc\uac04')),
                ('blue_player', models.IntegerField(db_index=True, verbose_name='\ube14\ub8e8 \ud50c\ub808\uc774\uc5b4 id')),
                ('red_player', models.IntegerField(db_index=True, verbose_name='\ub808\ub4dc \ud50c\ub808\uc774\uc5b4 id')),
                ('blue_score', models.IntegerField(verbose_name='\ube14\ub8e8 \uc810\uc218')),
                ('red_score', models.IntegerField(verbose_name='\ub808\ub4dc \uc810\uc218')),
                ('is_single', models.BooleanField(db_index=True, verbose_name='\uc2f1\uae00\ud50c\ub808\uc774 \uc5ec\ubd80')),
                ('blue_rating_old', models.FloatField(default=0.0, verbose_name='\ube14\ub8e8 \uc774\uc804 \ub808\uc774\ud305')),
                ('red_rating_old', models.FloatField(default=0.0, verbose_name='\ub808\ub4dc \uc774\uc804 \ub808\uc774\ud305')),
                ('blue_rating_delta', models.FloatField(verbose_name='\ube14\ub8e8 \uc810\uc218 \ubcc0\ub3d9')),
                ('red_rating_delta', models.FloatField(verbose_name='\ub808\ub4dc \uc810\uc218 \ubcc0\ub3d9')),
            ],
        ),
    ]
